config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  # surveys
  get 'surveys/:id/preview' => 'surveys#preview'
  get 'surveys/link'
  get 'surveys/:id/result' => 'surveys#result'

  # responser
  get 'responsers/index'
  get 'responsers/new'
  post 'responsers/r_create'
  
  #post 'questions/create/:params' => 'questions#create'#, as: 'question_create'
  #post 'questions/create' # 이렇게 하는게 아닌거 같음
  
  resources :surveys do
    resources :questions, except: [:show]

    get 'questions/preview/:id' => 'questions#preview', as: 'q_preview'
    get 'questions/etc'
    post 'questions/create' => 'questions#create'
    post 'questions/preview_update/:id' => 'questions#preview_update', as: 'q_p_update'
  end

  ## 설문 응답자
  get 'surveys/:survey_id/responsers' => 'responsers#index'
  get 'surveys/:survey_id/responsers/new' => 'responsers#new'
  post 'surveys/:survey_id/responsers' => 'responsers#r_create', as: 'responser_create'
  get 'surveys/:survey_id/responsers/question/:order' => 'responsers#question', as: 'r_q_order'
  post 'responsers/question/:id/answer' => 'responsers#answer', as: 'responsers_answer'
  post 'responsers/question/:id/thanks' => 'responsers#thanks', as: 'responsers_thanks'
  
  # -----
  #     ## 설문 응답자
  #   resources :responsers
  #   # get 'responsers/questions/:id' => 'responsers#questions', as: 'q_responser'
  #   get 'responsers/new' => 'responsers#new'
  #   get 'responsers/question/:id' => 'responsers#question', as: 'r_q_order'
  #   post 'responsers/answer'
  # ------
 
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  #devise_for :users 
  #resources :posts
  #resources :posts do
    #resources :comments
  #end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :multiple_choices, dependent: :destroy
    has_many :answers, dependent: :destroy
    
    ## [강사 Comment] Question 모델 참고를 위해 추가 생성
    ## 해당 설정이 사용되는 예시(questions/preview.html.erb) : <%= @q_preview.survey.title %>
    belongs_to :survey
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_survey, only: [:new, :create, :subjective]
    
    def index
        @new = params[:survey_id]
        redirect_to new_survey_question_path()
    end

    def create
        @count = params[:question_cnt].to_i ## integer로 변환
        
        for i in 1..@count
            @question = "question"+i.to_s
            #@survey = Question.create(survey_id: params[:survey_id], question_content: params[@question], order: i)
            Question.create(survey_id: params[:survey_id], question_content: params[@question], order: i)
            
            total_count = Survey.find_by(id: params[:survey_id])
            total_count.update(total_count: params[:total_count])
        end
        redirect_to "/"
    end

    private
    def find_survey
      @survey = Survey.find(params[:survey_id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/etc.html.erb
<!--기타-->
<!--옆에 미리보기 있으면 좋음-->
<br><br><br>
<1> <2> ..... n

<div style = "background-color : beige">
<h1>질문을 입력해주세요.</h1>
질문입력칸 넣기
</div>

<div style = "background-color : #fff0f6">
        <h4>답변형식</h4>
     <br>
    v 날짜<br>
    v 시간<br>
    v 표

    <div style = "background-color : #fcc2d7">
        옵션 넣기
    </div>
</div>

<%#= link_to "다음 질문만들기", new_survey_question_path %> <br>
<%#= link_to "완성하기", surveys_preview_path %>

app/views/questions/multiple.html.erb
<!--객관식-->
<!--옆에 미리보기 있으면 좋음-->
<br><br><br>
<1> <2> ..... n

<div style = "background-color : beige">
<h1>질문을 입력해주세요.</h1>
질문입력칸 넣기
</div>

<div style = "background-color : #fff0f6">
    <h4>답변</h4>
     <br>
    0. 내용 <br>
    0. 내용 <br>
    ㄴ multiple choice 연결
.<br>
.<br>
0. 기타: _____
    <div style = "background-color : #fcc2d7">
        <h5>detail</h5>
        1개만 선택 가능<br>
        여러개 선택 가능 : 0개까지
    </div>
</div>

<%#= link_to "다음 질문만들기", new_survey_question_path %> <br>
<%#= link_to "완성하기", surveys_preview_path %>

app/views/questions/new.html.erb
<script>
        var question = 0;
        var answer = 0;
        var button_status = [""];
        
        // question_content functions
        function short_text(){   
            question += 1;

            var colorCode = "#" + Math.round(Math.random() * 0xffffff).toString(16);
            
            var i = document.createElement("input");
            var m = document.createElement("input");
            var n = document.createElement("input");
            var k = document.createTextNode("Q"+question+". ");
            var j = document.createElement("br");
            var l = document.createElement("br");
            
            i.type = "text";
            i.name = "question"+question;
            i.id = "question"+question;
            i.size = 50;
            i.value = "";
            i.style.color = colorCode;
            
            m.type = "button";
            m.value = "짧은답변";
            // m.onclick = button_value(1);
            m.addEventListener('click', function() {
                button_status.push("짧은답변");
            });
            
            n.type = "button";
            n.value = "긴답변";
            n.addEventListener('click', function() {
                button_status.push("긴답변");
            });
            
            
            document.getElementById("sendQuestion_div").appendChild(k);
            document.getElementById("sendQuestion_div").appendChild(i);
            document.getElementById("sendQuestion_div").appendChild(m);
            document.getElementById("sendQuestion_div").appendChild(n);
            document.getElementById("sendQuestion_div").appendChild(j);
            document.getElementById("sendQuestion_div").appendChild(l);
        } 

        /*        
        function long_text(){ 
            question += 1;

            var colorCode = "#" + Math.round(Math.random() * 0xffffff).toString(16);
            
            var k = document.createTextNode("Q"+question+". ");
            var i = document.createElement("textarea");
            var j = document.createElement("br");
            var l = document.createElement("br");
            var m = document.createElement("br");

            i.name = "question"+question;
            i.id = "question"+question;
            i.size = 50;
            i.value = "";
            i.style.color = colorCode;
            i.cols = 40;
            i.rows = 8;
                
            document.getElementById("sendQuestion_div").appendChild(k);
            document.getElementById("sendQuestion_div").appendChild(m);
            document.getElementById("sendQuestion_div").appendChild(i);
            document.getElementById("sendQuestion_div").appendChild(j);
            document.getElementById("sendQuestion_div").appendChild(l);
        } 
        */
        
        
        ///////////////////// answer_functions ///////////////////////
        /*
        function short_text_answer(){
            answer += 1;

            var j = document.createElement("br");
            var i = document.createElement("input");
            var k = document.createElement("br");
            
            i.type = "hidden";
            i.name = "answer"+answer;
            i.size = 50;
            i.value = "";

            document.getElementById("sendQuestion_answer_div").appendChild(k);
            document.getElementById("sendQuestion_answer_div").appendChild(i);
            document.getElementById("sendQuestion_answer_div").appendChild(j);
        }
        */

        /*
        function long_text_answer(){
            answer += 1;

            var j = document.createElement("br");
            var i = document.createElement("textarea");
            var k = document.createElement("br");
            
            i.hidden = "hidden";
            i.name = "answer"+answer;
            //i.size = 50;
            i.value = "";
            //i.cols = 40;
            //i.rows = 8;

            document.getElementById("sendQuestion_answer_div").appendChild(k);
            document.getElementById("sendQuestion_answer_div").appendChild(i);
            document.getElementById("sendQuestion_answer_div").appendChild(j);
        }
        */

        
        function total_question_count(){
            var total_count_for_send = document.createElement("input");
            total_count_for_send.name = "question_cnt" // 질문 수 카운트를 위한 
            total_count_for_send.type="hidden";
            total_count_for_send.value = question;
            document.getElementById("sendQuestion_div").appendChild(total_count_for_send);
        }


        function modallist(){

            for(var x=1; x<=question; x++){
                
                var a = document.createElement("h3");
                var c = document.createElement("input");
                var b = document.createElement("br");
                var e = document.createElement("br");
                

                var temp = document.getElementById("question"+x);
                var temp2 = document.createTextNode("Q"+x+". "+temp.value);
                a.appendChild(temp2);
                
                c.type = "button";
                c.value = button_status[x];
                if (c.value == "undefined") {
                      c.value = "답변길이를 설정하지 않았습니다.";
                }

                document.getElementById("modal-question").appendChild(a);
                document.getElementById("modal-question").appendChild(c);
                document.getElementById("modal-question").appendChild(b);
                document.getElementById("modal-question").appendChild(e);
            
            }
        }

        function modallist_clear(){           
            var x = document.getElementById("modal-question");
            while(x.hasChildNodes()){
                x.removeChild(x.firstChild);
            }
        }
        
    </script>

<!-- -->

<!--body 시작-->
<div class="center">
<h1>취합명: <%= @survey.title %></h1>
<br>


                <form action="/surveys/<%= params[:survey_id]%>/questions" id="sendQuestion" name="sendQuestion" method="POST">
                
                <input type="hidden" name="survey_id" value=<%= params[:survey_id] %>></input><br>

                <div id="sendQuestion_div"></div>
                <h2>어떤 종류의 질문을 만드시겠습니까?</h2>
                
                <button type="button" class="btn2 btn-info btn-lg"  onclick="">객관식</button>
                <button type="button" class="btn2 btn-info btn-lg"  onclick=short_text();>주관식</button>
                <button type="button" class="btn2 btn-info btn-lg"  onclick="">기타</button>
                
                <!--<div id="sendQuestion_answer_div"></div><hr>-->
                <br><br>
                <span>원하는 취합 수</span>
                <input type="number" name="total_count" max="100" placeholder="(옵션)"></input><br><br>
 
                <!-- question send button-->
                <!--<button type="submit" onclick=total_question_count(); class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal1">작성완료</button>-->
                
                <!-- Modal -->
                <div class="modal fade" id="myModal2" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">미리보기</h4>
                            </div>
                            <div class="modal-body" id="modal-question" align="left"> <!-- modal body-->
                            </div>
                            <div class="modal-footer">
                                <button type="button" onclick=modallist_clear(); class="btn btn-default" data-dismiss="modal">닫기</button>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                <!-- Modal -->
                <div class="modal fade" id="myModal1" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">링크생성</h4>
                            </div>
                            <div class="modal-body" id="modal-link" align="center"> <!-- modal body-->
                            <h2>
                            https://163b6a0f822f49158af328354cd4e277.vfs.cloud9.ap-northeast-1.amazonaws.com/responsers/index?survey_id=<%= params[:survey_id] %>
                            </h2>
                                
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
                            </div>
                        </div>
                    </div>
                </div>
                

                <br>                            

                <!-- modal preview button-->
                <button type="button" onclick=modallist(); class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal2">미리보기</button>
                <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal1">공유링크</button>
                <button type="submit" onclick=total_question_count(); class="btn btn-info btn-lg" data-toggle="modal">작성완료</button> 
                <%= link_to "취소하기", "/surveys/#{@survey.id}", method: :delete, class:"btn btn-info btn-lg"%>
                
            <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" /> <!--form post token-->
            </form>
        
<br>
<br>

</div>

<style>

  .center {
    text-align: center;
    margin-top: 100px;
  }
  
  .bigfont{
      font-size: 60px;
  }
  
  .btn {
  font-size: 20px;
  text-transform: capitalize;
  padding: 10px 30px;
  border-radius: 5px;
  font-weight: 600;
  border: 0;
  position: relative;
  z-index: 1;
  transition: .2s ease;
  background: #41228e;
  margin: 5px;

  &:focus {
    outline: 0;
    box-shadow: none !important;
  }
  
    .btn2 {
  font-size: 20px;
  text-transform: capitalize;
  padding: 10px 30px;
  border-radius: 5px;
  font-weight: 600;
  border: 0;
  position: relative;
  z-index: 1;
  transition: .2s ease;
  background: #ee519d;
  margin: 5px;

  &:focus {
    outline: 0;
    box-shadow: none !important;
  }
  
  
  .btn-primary {
  background: $primary-color;
  color: $white;

  &:active {
    background: lighten($color: $primary-color, $amount: 10) !important;
  }

  &:hover {
    background: lighten($color: $primary-color, $amount: 10);
  }

  &.focus,
  &.active {
    background: lighten($color: $primary-color, $amount: 10) !important;
    box-shadow: none !important;
  }
  }
  
 .textfield-btn {
    height: 40px;
    width: 120px;
    padding-right: 2px;
    background: rgb(221, 221, 221);
 }
 
 .textfield-text {
    padding: 12px 8px;
    margin: 4px;
    border: none;
    color: #542cb7;
    font-size: 42% ;
    font-family: "S-CoreDream-4Regular";
    font-weight: 600;
    border-radius: 5px;
    text-align: center;
 }
  
</style>

app/views/questions/subjective.html.erb
<!--주관식-->
<!--옆에 미리보기 있으면 좋음-->
<br><br><br>
<1> <2> ..... n

<div style = "background-color : beige">
<h1>질문을 입력해주세요.</h1>
  
 
</div>

<%= form_tag("/surveys/#{params[:survey_id]}/questions", method: :post) do %>
  <%= label_tag :title %>
  <%= text_field_tag :title %>
      
  <div style = "background-color : #fff0f6">
    <h4>답변형식</h4>
    <br>
    v 짧은 답변<br>
    v 긴 답변
    
    <div style = "background-color : #fcc2d7">
      옵션 넣기<br>
      허용할 것 : 문자 / 숫자/ 특수문자 <br>
      금지어<br>
      글자수 제한
    </div>
  </div>

  <div><%= submit_tag '다음질문 만들기' %></div>
<% end %>


<%#= link_to "다음 질문만들기", new_survey_question_path %> <br>