config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  # surveys
  get 'surveys/:id/preview' => 'surveys#preview'
  get 'surveys/link'
  get 'surveys/:id/result' => 'surveys#result'

  # responser
  get 'responsers/index'
  get 'responsers/new'
  post 'responsers/r_create'
  
  #post 'questions/create/:params' => 'questions#create'#, as: 'question_create'
  #post 'questions/create' # 이렇게 하는게 아닌거 같음
  
  resources :surveys do
    resources :questions, except: [:show]

    get 'questions/preview/:id' => 'questions#preview', as: 'q_preview'
    get 'questions/etc'
    post 'questions/create' => 'questions#create'
    post 'questions/preview_update/:id' => 'questions#preview_update', as: 'q_p_update'
  end

  ## 설문 응답자
  get 'surveys/:survey_id/responsers' => 'responsers#index'
  get 'surveys/:survey_id/responsers/new' => 'responsers#new'
  post 'surveys/:survey_id/responsers' => 'responsers#r_create', as: 'responser_create'
  get 'surveys/:survey_id/responsers/question/:order' => 'responsers#question', as: 'r_q_order'
  post 'responsers/question/:id/answer' => 'responsers#answer', as: 'responsers_answer'
  post 'responsers/question/:id/thanks' => 'responsers#thanks', as: 'responsers_thanks'
  
  # -----
  #     ## 설문 응답자
  #   resources :responsers
  #   # get 'responsers/questions/:id' => 'responsers#questions', as: 'q_responser'
  #   get 'responsers/new' => 'responsers#new'
  #   get 'responsers/question/:id' => 'responsers#question', as: 'r_q_order'
  #   post 'responsers/answer'
  # ------
 
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  #devise_for :users 
  #resources :posts
  #resources :posts do
    #resources :comments
  #end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/responser.rb
class Responser < ApplicationRecord
    belongs_to :survey
end

app/controllers/responsers_controller.rb
class ResponsersController < ApplicationController
    def index
        # @questions = Question.where(survey_id: params[:survey])
        @survey_title = Survey.find_by(id: params[:survey_id]).title
        # @servey_id = Survey.find_by(id: params[:survey_id]).id
        @survey = Survey.find(params[:survey_id])
        @responser = Responser.new
        # @responser.nickname = params[:nickname]
        # @responser.password = params[:password]
        # @responser.save
        # redirect_to responsers_new_path
        # redirect_to survey_r_q_order_path(:id)

    end
    
    def r_create
        @responser = Responser.new
        @responser.nickname = params[:responser][:nickname]
        @responser.password = params[:responser][:password]
        @responser.survey_id = params[:survey_id]
        @responser.save
        # @survey = Survey.find(params[:survey_id])
        # survey = params[:survey_id]
        redirect_to r_q_order_path(params[:survey_id], 1)
    end
    
    def new
        @number = @number + 1
        @question = Question.find_by(id: @number)
        # id가 아니라 해당 survey의 order가 1인걸로 바꿔줘야함
        @number_plus = @number + 1
        @question_plus = Question.find_by(id: @number_plus)
        redirect_to responsers_new_path (@number)
    end
    
    def question
        @answer = Answer.new
        @question = Question.find_by(survey_id: params[:survey_id], order: params[:order])
                
        if Question.find_by(survey_id: @question.survey_id, order: @question.order + 1).nil?
            @is_last_order = true
        else
            @is_last_order = false
        end
    end
    
    def answer
        @answer = Answer.create(
            question_id: params[:id], 
            content: params[:answer][:content])
        @question = @answer.question
        redirect_to r_q_order_path(@question.survey_id, @question.order + 1)
        # surveys/:survey_id/responsers/question/:order

        
    end
    
    def thanks
        @answer = Answer.create(
            question_id: params[:id], 
            content: params[:answer][:content])
        
        @a = Question.find(params[:id]).survey
        @a.update(current_count: @a.current_count+1)

    end
end

app/helpers/responsers_helper.rb
module ResponsersHelper
end

app/views/responsers/answer.html.erb
answer

app/views/responsers/index.html.erb
<!--responser의 index 뷰-->
<div class= "login-form">
    <div class = "title">
        <%= @survey_title %>
    </div>
    <hr>
    <%= form_for @responser, url: responser_create_path(@survey.id), method: "post" do |f| %>
        <div class = "explain">취합에 응답하거나 수정하려면 입력해주세요.</div>
        <!--이후 수정을 위해서는 꼭 닉네임, 비밀번호를 기억해주세요.-->
        <div class="form-group">
            <%= f.text_field :nickname, placeholder: "닉네임" %>
        </div>
        <div class="form-group">
            <%= f.password_field :password, placeholder: "비밀번호" %><br>
        </div>
        <div class="form-group">
            <%= f.submit "설문에 대답하기", class: "submit"  %>
        </div>
    <% end %>
</div>

<style>
    .navbar {
        visibility: hidden;
    }
    body{
    min-height: 100vh;
    background-image: linear-gradient(120deg, #f37351, #422e8a);
    }
    .login-form{
    width: 40%;
    background: #f1f1f1;
    height: 370px;
    padding: 80px 40px;
    border-radius: 10px;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
    }
    .title {
        font-size: 30px;
        font-weight: 700;
    }
    .explain {
        font-size: 14px;
        padding: 6px 0 12px 0;
    }
    .form-group {
        font-size: 19px;
        margin: 4px 0;
    }
    .submit {
        padding: 3px 39px;
    }

</style>

app/views/responsers/new.html.erb
<!--responser 컨트롤러의 new-->
<!--여기에 여러개의 answer을 연결-->
<!--질문question을 하나씩 불러오고-->
<!--답변하는 칸을 만든다. answer을 db로 전송-->

<!--question의 order가 1인 것을 불러옴-->
<!--그에 맞는 답변칸을 만듬-->

<!--question의 order가 1+1인 것을 불러옴-->
<!--그에 맞는 답변칸을 만듬-->


<%= @question.question_content %><br>
<%= @question.question_subcontent %><br>
질문order1대한 answer을 입력하는 칸

<hr>
    <%= @number = @number + 1 %>
    <%= @number_plus %>
    <hr>
<button>
    다음

</button>

<button name="button" type="submit">다음</button>
다음버튼. 이 버튼을 누를때마다 order에 1을 더해준다

<button_tag "다음" ></button_tag>

if order is last
    끝 버튼
elsif 
    다음버튼
<%#= form_for @number, url:  


<% end %>

app/views/responsers/question.html.erb
<!--responser 컨트롤러의 new-->
<!--여기에 여러개의 answer을 연결-->

<div class= "login-form">
    <div class = "title">
        <%= @question.question_content %><br>
    </div>
    <%#= @question.question_subcontent %><br>

    <%#= form_tag responsers_answer_path(@question.id), method: "post" %>
        <%#= text_field_tag :content %>
        <%#= submit_tag %>
    <%# end %>

    <% if @is_last_order %>
        <%= form_for @answer, url: responsers_thanks_path(@question.id), method: "post" do |f| %>
            <%= f.text_field :content %><br>
            <%= f.submit "완료", class: "submit" %>
        <% end %>
    <% else %>
        <%= form_for @answer, url: responsers_answer_path(@question.id), method: "post" do |f| %>
            <%= f.text_field :content %><br>
            <%= f.submit "다음", class: "submit" %>
        <% end %>
    <% end %>

</div>

<style>
    .navbar {
        visibility: hidden;
    }
    body{
    min-height: 100vh;
    background-image: linear-gradient(120deg, #f37351, #422e8a);
    }
    .login-form{
    width: 40%;
    background: #f1f1f1;
    height: 330px;
    padding: 80px 40px;
    border-radius: 10px;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
    }
    .title {
        font-size: 30px;
        font-weight: 700;
    }
    .submit {
        margin-top: 10px;
        padding: 3px 20px;
    }
    
</style>

app/views/responsers/thanks.html.erb
<section class="hero-area" id="parallax">
    <!--<div class= "login-form">-->
        <div class= "text1">감사합니다!</div>
    <!--</div>-->
  <!--<div class="layer-bg w-100">-->
  <!--  <img class="img-fluid w-100" src="<%= asset_path 'leaf-bg.png' %>" alt="bg-shape">-->
  <!--</div>-->
  <div class="layer" id="l2">
    <img src="<%= asset_path 'dots-cyan.png' %>" alt="bg-shape">
  </div>
  <div class="layer" id="l3">
    <img src="<%= asset_path 'leaf-orange.png' %>" alt="bg-shape">
  </div>
  <div class="layer" id="l4">
    <img src="<%= asset_path 'dots-orange.png' %>" alt="bg-shape">
  </div>
  <div class="layer" id="l5">
    <img src="<%= asset_path 'leaf-yellow.png' %>" alt="bg-shape">
  </div>
  <div class="layer" id="l6">
    <img src="<%= asset_path 'leaf-cyan.png' %>" alt="bg-shape">
  </div>
  <div class="layer" id="l7">
    <img src="<%= asset_path 'dots-group-orange.png' %>" alt="bg-shape">
  </div>
  <div class="layer" id="l8">
    <img src="<%= asset_path 'leaf-pink-round.png' %>" alt="bg-shape">
  </div>
  <div class="layer" id="l9">
    <img src="<%= asset_path 'leaf-cyan-2.png' %>" alt="bg-shape">
  </div>
</section>


<script>
/* ########################################### hero parallax ############################################## */
    window.onload = function () {

        var parallaxBox = document.getElementById('parallax');
        var
            /* c1left = document.getElementById('l1').offsetLeft,
                       c1top = document.getElementById('l1').offsetTop, */
            c2left = document.getElementById('l2').offsetLeft,
            c2top = document.getElementById('l2').offsetTop,
            c3left = document.getElementById('l3').offsetLeft,
            c3top = document.getElementById('l3').offsetTop,
            c4left = document.getElementById('l4').offsetLeft,
            c4top = document.getElementById('l4').offsetTop,
            c5left = document.getElementById('l5').offsetLeft,
            c5top = document.getElementById('l5').offsetTop,
            c6left = document.getElementById('l6').offsetLeft,
            c6top = document.getElementById('l6').offsetTop,
            c7left = document.getElementById('l7').offsetLeft,
            c7top = document.getElementById('l7').offsetTop,
            c8left = document.getElementById('l8').offsetLeft,
            c8top = document.getElementById('l8').offsetTop,
            c9left = document.getElementById('l9').offsetLeft,
            c9top = document.getElementById('l9').offsetTop;

        parallaxBox.onmousemove = function (event) {
            event = event || window.event;
            var x = event.clientX - parallaxBox.offsetLeft,
                y = event.clientY - parallaxBox.offsetTop;

            /*  mouseParallax('l1', c1left, c1top, x, y, 5); */
            mouseParallax('l2', c2left, c2top, x, y, 25);
            mouseParallax('l3', c3left, c3top, x, y, 20);
            mouseParallax('l4', c4left, c4top, x, y, 35);
            mouseParallax('l5', c5left, c5top, x, y, 30);
            mouseParallax('l6', c6left, c6top, x, y, 45);
            mouseParallax('l7', c7left, c7top, x, y, 30);
            mouseParallax('l8', c8left, c8top, x, y, 25);
            mouseParallax('l9', c9left, c9top, x, y, 40);
        };

    };

    function mouseParallax(id, left, top, mouseX, mouseY, speed) {
        var obj = document.getElementById(id);
        var parentObj = obj.parentNode,
            containerWidth = parseInt(parentObj.offsetWidth),
            containerHeight = parseInt(parentObj.offsetHeight);
        obj.style.left = left - (((mouseX - (parseInt(obj.offsetWidth) / 2 + left)) / containerWidth) * speed) + 'px';
        obj.style.top = top - (((mouseY - (parseInt(obj.offsetHeight) / 2 + top)) / containerHeight) * speed) + 'px';
    }
    /* ########################################### /hero parallax ############################################## */
  
</script>

<style>
  /*  typography */
  @import url("https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Roboto:300,400,500,700");
    
    .navbar {
        visibility: hidden;
    }
  .hero-area {
    padding: 300px 0 200px;
    position: relative;
    @include tablet {
      padding: 250px 0 150px;
      overflow: hidden;
    }
  }
  body{
    min-height: 100vh;
    background-image: linear-gradient(120deg, #f37351, #422e8a);
    }
  .text1 {
      position: relative;
      z-index: 1;
      font-family: "S-CoreDream-4Regular";
      font-size: 70px;
      font-weight: 700 ;
      text-align: center;
      color: white;
  }
  /*.bg-primary {*/
  /*  background: #41228e !important;*/
  /*}*/
  
  .layer {
    position: absolute;
    z-index: 1;
  }
  
  .layer-bg {
    position: absolute;
    bottom: 0;
    left: 0;
  }
  
  .button-big {
    text-transform: capitalize;
    padding: 16px 44px;
    border-radius: 5px;
    border: 0;
    position: relative;
    z-index: 1;
    transition: .2s ease;
    background-color: rgb(221, 221, 221);
    font-family: "S-CoreDream-4Regular";
    font-weight: 600;
    font-size: 40% ;
    color: #542cb7;
  }
  
  .textfield {
    text-transform: capitalize;
    margin-top: 20px;
    position: relative;
    z-index: 1;
    transition: .2s ease;
  }
  
  .textfield-text{
    padding: 12px 8px;
    margin: 0 4px;
    border: none;
    color: #542cb7;
    font-size: 150% ;
    font-family: "S-CoreDream-4Regular";
    font-weight: 600;
    border-radius: 5px;
    text-align: center;
  }
  
  ::placeholder {
    font-weight: 400;
  }
  
  .textfield-btn {
    height: 64px;
    width: 120px;
    padding-right: 2px;
    background: rgb(221, 221, 221);
  }
  
  .login-form{
      z-index: 1;
    width: 40%;
    background: #f1f1f1;
    height: 150px;
    padding: 80px 40px;
    border-radius: 10px;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
    }
    
  #l1 {
    bottom: 0;
    left: 0;
  }
  
  #l2 {
    top: 190px;
    left: -250px;
  }
  
  #l3 {
    top: 200px;
    left: 40%;
  }
  
  #l4 {
    top: 200px;
    right: 40%;
  }
  
  #l5 {
    top: 100px;
    right: -150px;
  }
  
  #l6 {
    bottom: -20px;
    left: 10%;
  }
  
  #l7 {
    bottom: 100px;
    left: 20%;
  }
  
  #l8 {
    bottom: 160px;
    right: 45%;
  }
  
  #l9 {
    bottom: 100px;
    right: -10px;
  }

</style>