config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  # surveys
  get 'surveys/:id/preview' => 'surveys#preview'
  get 'surveys/link'
  get 'surveys/:id/result' => 'surveys#result'

  # responser
  get 'responsers/index'
  get 'responsers/new'
  post 'responsers/r_create'
  
  #post 'questions/create/:params' => 'questions#create'#, as: 'question_create'
  #post 'questions/create' # 이렇게 하는게 아닌거 같음
  
  resources :surveys do
    resources :questions, except: [:show]

    get 'questions/preview/:id' => 'questions#preview', as: 'q_preview'
    get 'questions/etc'
    post 'questions/create' => 'questions#create'
    post 'questions/preview_update/:id' => 'questions#preview_update', as: 'q_p_update'
  end

  ## 설문 응답자
  get 'surveys/:survey_id/responsers' => 'responsers#index'
  get 'surveys/:survey_id/responsers/new' => 'responsers#new'
  post 'surveys/:survey_id/responsers' => 'responsers#r_create', as: 'responser_create'
  get 'surveys/:survey_id/responsers/question/:order' => 'responsers#question', as: 'r_q_order'
  post 'responsers/question/:id/answer' => 'responsers#answer', as: 'responsers_answer'
  post 'responsers/question/:id/thanks' => 'responsers#thanks', as: 'responsers_thanks'
  
  # -----
  #     ## 설문 응답자
  #   resources :responsers
  #   # get 'responsers/questions/:id' => 'responsers#questions', as: 'q_responser'
  #   get 'responsers/new' => 'responsers#new'
  #   get 'responsers/question/:id' => 'responsers#question', as: 'r_q_order'
  #   post 'responsers/answer'
  # ------
 
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  #devise_for :users 
  #resources :posts
  #resources :posts do
    #resources :comments
  #end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord
    has_many :questions, dependent: :destroy
    #  has_many에 :responsers도 추가해야 함
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :find_survey_id, only: [:show, :destroy, :preview, :result]
    
  def index
    @surveys = Survey.where(user_id: User.find_by(email: current_user.email)) 
    #자신의 계정에만 해당하는 설문 리스트 출력
  end
  
  def new
    
  end
  
  def create
    @survey = Survey.create(
      title: "#{params[:survey][:title]}",
      user_id: User.find_by(email: current_user.email).id
    )
    #현재 계정의 user_id 값을 넣음 question을 추가 안해도 설문이 바로 생성되는 부분 수정필요로 보임
    redirect_to survey_questions_path(@survey)
  end
  
  def show
    @questions = @survey.questions
  end
  
  def result
    @questions = @survey.questions
  end
  
  def destroy
    @survey.delete
    redirect_to '/'
  end
  
  def preview
    
  end
  
  def link
  
  end
  
  private
  def find_survey_id
    @survey = Survey.find(params[:id])
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/detail.html.erb
<h1>만든 설문 자세히 보기</h1>

수정하기(questions의 new쪽으로) <br>
<%= link_to "결과보기", surveys_result_path %>

app/views/surveys/index.html.erb
<div class="font">
<h1 align= "center">내 취합 목록</h1>
<div align= "right"><%= link_to "새 취합하기", root_path, class:"btn" %></div>
<br>

<!--각 취합내용-->
<%= @text %>
<% @surveys.each do |s| %>
    <span class="title-black">취합명:</span>
    <span class="title"><%= s.title %></span>
    <button type="button" class="link-btn btn-info btn-lg" data-toggle="modal" data-target="#myModal<%=s.id%>"><i class="fas fa-share-alt"> 배포링크</i></button>
   <!-- Modal -->
        <div class="modal fade" id="myModal<%=s.id%>" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">링크보기</h4>
                    </div>
                    <div class="modal-body" id="modal-link" align="center"> <!-- modal body-->
                    <h2>
                    https://163b6a0f822f49158af328354cd4e277.vfs.cloud9.ap-northeast-1.amazonaws.com/responsers/index?survey_id=<%= s.id %>
                    </h2>
                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
                    </div>
                </div>
            </div>
        </div>
    <span class="small-title">개설일 : <%= s.created_at.strftime("%y. %m. %d") %></span>
      <br>
    <div class="blank">
        <%= link_to "자세히 보기", survey_path(s), class: "small-btn btn-info btn-lg" %>
        <%= link_to "결과보기", surveys_link_path(s), class: "small-btn btn-info btn-lg" %>
        <%= link_to "삭제하기", survey_path(s), method: :delete, id: "becareful", class: "small-btn btn-info btn-lg"  %>
    </div>

    <hr>
<% end %>



</div>

<script>
    
</script>


<script> function btn()
    { }
</script>

<style>
 .font {
  font-family: 'S-CoreDream-4Regular';
 }

  .center {
    text-align: center;
  }
  
  .bigfont{
      font-size: 60px;
  }
  
 .btn {
  font-size: 20px;
  text-transform: capitalize;
  padding: 10px 30px;
  border-radius: 5px;
  font-weight: 600;
  border: 0;
  position: relative;
  z-index: 1;
  transition: .2s ease;
  background: #41228e;
  margin: 5px;
  color: white;


  &:focus {
    outline: 0;
    box-shadow: none !important;
  }
 }
  
 .btn2 {
  font-size: 20px;
  text-transform: capitalize;
  padding: 10px 30px;
  border-radius: 5px;
  font-weight: 600;
  border: 0;
  position: relative;
  z-index: 1;
  transition: .2s ease;
  background: #ee519d;
  margin: 5px;

  &:focus {
    outline: 0;
    box-shadow: none !important;
  }
 } 
  
  .btn-primary {
  background: $primary-color;
  color: $white;

  &:active {
    background: lighten($color: $primary-color, $amount: 10) !important;
  }

  &:hover {
    background: lighten($color: $primary-color, $amount: 10);
  }

  &.focus,
  &.active {
    background: lighten($color: $primary-color, $amount: 10) !important;
    box-shadow: none !important;
  }
  }
  /*body {*/
  /*    background: #d0bfff;*/
  /*}*/
 .blank {
     margin-top: 10px;
 }
 
 .small-btn {
    height: 30px;
    width: 100px;
    background: rgb(221, 221, 221);
    padding: 5px 70px;
    border: none;
    color: #542cb7;
    font-size: 90% ;
    font-family: "S-CoreDream-4Regular";
    font-weight: 600;
    border-radius: 5px;
    text-align: center;
 }
 
 
 .title {
     font-family: "S-CoreDream-8Heavy";
     color: #542cb7
 }
 
  .title-black {
     font-family: "S-CoreDream-8Heavy";
     color: black;
 }
 
 .small-title {
     font-size: 13px;
     font-weight: 500;
     color: grey;
 }
 
 .link-btn {
    color: white;
    padding: 7px 10px;
    border: none;
    background: #542cb7;
    font-size: 40% ;
    border-radius: 5px;
    text-align: center;
 }
     .font {
         margin-top: 120px;

     }
     
 #becareful {
     background: red;
     color: white;
 }
 
 </style>

app/views/surveys/link.html.erb
<div class="a">
<%= bar_chart Survey.where.not(total_count: nil).group(:total_count).sum(:current_count) %>
<%= link_to "처음으로 돌아가기", root_path %>
</div>

<style>
    .a {
        margin-top: 100px;
        width: 95%;
    }
</style>

app/views/surveys/preview.html.erb
<h1>취합 미리보기</h1>
<h3> <%= @survey.title %> </h3>
<hr>

<% @survey.questions.each do |x| %>
        <%= x.question_content %>
        <br><input type="text">
        <hr/>
<% end %>

<br>
<br>
<%= link_to "이전으로", "/surveys/#{@survey.id}/questions/new" %>
<%= link_to "배포하기", surveys_link_path %>
<script>alert("https://163b6a0f822f49158af328354cd4e277.vfs.cloud9.ap-northeast-1.amazonaws.com/responsers/index?survey="+<%= @survey.id %>)</script>

app/views/surveys/result.html.erb
<h1><%= @survey.title %></h1>

<br>
(답변 개수)<br>
엑셀추출<br>

<div>
    <span class='blue' data-val='20%'>찬성</span>
    <span class='red' data-val='80%'>반대</span>
</div> 

<style>
    div {
        margin: 150px 10px;
        border: 1px solid black;
        padding: 3px;
        font-size: 0;
    }
    
    span {
        display: inline-block;
        color: #fff;
        font-size: 20px;
        line-height: 1.8em;
        text-align: center;
    }
    .blue {
        background: #00f;
    }
    
    .red {
        background: #f00;
        float: right;
    }
</style>

<script>
d3.selectAll('span')
    .datum(function(){return this.dataset})
    .style('widht','50%')
    .transition().duration(2000)
    .style('width', d=>d.val)

    
</script>

app/views/surveys/show.html.erb
<%= @survey.title %>
<% @questions.each do |question| %>
    <p><%= question.order %></p>
    <p><%= question.question_content %></p>
<% end %>