config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  # surveys
  get 'surveys/:id/preview' => 'surveys#preview'
  get 'surveys/link'
  get 'surveys/:id/result' => 'surveys#result'

  # responser
  get 'responsers/index'
  get 'responsers/new'
  post 'responsers/r_create'
  
  #post 'questions/create/:params' => 'questions#create'#, as: 'question_create'
  #post 'questions/create' # 이렇게 하는게 아닌거 같음
  
  resources :surveys do
    resources :questions, except: [:show]

    get 'questions/preview/:id' => 'questions#preview', as: 'q_preview'
    get 'questions/etc'
    post 'questions/create' => 'questions#create'
    post 'questions/preview_update/:id' => 'questions#preview_update', as: 'q_p_update'
  end

  ## 설문 응답자
  get 'surveys/:survey_id/responsers' => 'responsers#index'
  get 'surveys/:survey_id/responsers/new' => 'responsers#new'
  post 'surveys/:survey_id/responsers' => 'responsers#r_create', as: 'responser_create'
  get 'surveys/:survey_id/responsers/question/:order' => 'responsers#question', as: 'r_q_order'
  post 'responsers/question/:id/answer' => 'responsers#answer', as: 'responsers_answer'
  post 'responsers/question/:id/thanks' => 'responsers#thanks', as: 'responsers_thanks'
  
  # -----
  #     ## 설문 응답자
  #   resources :responsers
  #   # get 'responsers/questions/:id' => 'responsers#questions', as: 'q_responser'
  #   get 'responsers/new' => 'responsers#new'
  #   get 'responsers/question/:id' => 'responsers#question', as: 'r_q_order'
  #   post 'responsers/answer'
  # ------
 
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  #devise_for :users 
  #resources :posts
  #resources :posts do
    #resources :comments
  #end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    has_many :responsers, dependent: :destroy
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/multiple_choice.rb
class MultipleChoice < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :multiple_choices, dependent: :destroy
    has_many :answers, dependent: :destroy
    
    ## [강사 Comment] Question 모델 참고를 위해 추가 생성
    ## 해당 설정이 사용되는 예시(questions/preview.html.erb) : <%= @q_preview.survey.title %>
    belongs_to :survey
end

app/models/responser.rb
class Responser < ApplicationRecord
    belongs_to :survey
end

app/models/survey.rb
class Survey < ApplicationRecord
    has_many :questions, dependent: :destroy
    #  has_many에 :responsers도 추가해야 함
end

app/models/user.rb
class User < ApplicationRecord
  has_many :surveys, dependent: :destroy
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
 
  def self.find_for_oauth(auth, current_user)
        # 이미 있는 계정인지 확인한다.
        email = auth.info.email
        user = User.where(:email => email).first
        
        if not self.where(email: auth.info.email).exists?
            # 계정이 없다면 새로운 데이터를 생성한다.
            if user.nil?
                user = User.new(name: auth.info.name, email: email ? auth.info.email : "#{auth.uid}@#{auth.provider}.com", password: Devise.friendly_token[0,20])
                user.save!
            end
        end
    user
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @survey = Survey.new
  end
end

app/controllers/multiples_controller.rb
class MultiplesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_survey, only: [:new, :create, :subjective]
    
    def index
        @new = params[:survey_id]
        redirect_to new_survey_question_path()
    end

    def create
        @count = params[:question_cnt].to_i ## integer로 변환
        
        for i in 1..@count
            @question = "question"+i.to_s
            #@survey = Question.create(survey_id: params[:survey_id], question_content: params[@question], order: i)
            Question.create(survey_id: params[:survey_id], question_content: params[@question], order: i)
            
            total_count = Survey.find_by(id: params[:survey_id])
            total_count.update(total_count: params[:total_count])
        end
        redirect_to "/"
    end

    private
    def find_survey
      @survey = Survey.find(params[:survey_id])
    end
end

app/controllers/responsers_controller.rb
class ResponsersController < ApplicationController
    def index
        # @questions = Question.where(survey_id: params[:survey])
        @survey_title = Survey.find_by(id: params[:survey_id]).title
        # @servey_id = Survey.find_by(id: params[:survey_id]).id
        @survey = Survey.find(params[:survey_id])
        @responser = Responser.new
        # @responser.nickname = params[:nickname]
        # @responser.password = params[:password]
        # @responser.save
        # redirect_to responsers_new_path
        # redirect_to survey_r_q_order_path(:id)

    end
    
    def r_create
        @responser = Responser.new
        @responser.nickname = params[:responser][:nickname]
        @responser.password = params[:responser][:password]
        @responser.survey_id = params[:survey_id]
        @responser.save
        # @survey = Survey.find(params[:survey_id])
        # survey = params[:survey_id]
        redirect_to r_q_order_path(params[:survey_id], 1)
    end
    
    def new
        @number = @number + 1
        @question = Question.find_by(id: @number)
        # id가 아니라 해당 survey의 order가 1인걸로 바꿔줘야함
        @number_plus = @number + 1
        @question_plus = Question.find_by(id: @number_plus)
        redirect_to responsers_new_path (@number)
    end
    
    def question
        @answer = Answer.new
        @question = Question.find_by(survey_id: params[:survey_id], order: params[:order])
                
        if Question.find_by(survey_id: @question.survey_id, order: @question.order + 1).nil?
            @is_last_order = true
        else
            @is_last_order = false
        end
    end
    
    def answer
        @answer = Answer.create(
            question_id: params[:id], 
            content: params[:answer][:content])
        @question = @answer.question
        redirect_to r_q_order_path(@question.survey_id, @question.order + 1)
        # surveys/:survey_id/responsers/question/:order

        
    end
    
    def thanks
        @answer = Answer.create(
            question_id: params[:id], 
            content: params[:answer][:content])
        
        @a = Question.find(params[:id]).survey
        @a.update(current_count: @a.current_count+1)

    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :find_survey_id, only: [:show, :destroy, :preview, :result]
    
  def index
    @surveys = Survey.where(user_id: User.find_by(email: current_user.email)) 
    #자신의 계정에만 해당하는 설문 리스트 출력
  end
  
  def new
    
  end
  
  def create
    @survey = Survey.create(
      title: "#{params[:survey][:title]}",
      user_id: User.find_by(email: current_user.email).id
    )
    #현재 계정의 user_id 값을 넣음 question을 추가 안해도 설문이 바로 생성되는 부분 수정필요로 보임
    redirect_to survey_questions_path(@survey)
  end
  
  def show
    @questions = @survey.questions
  end
  
  def result
    @questions = @survey.questions
  end
  
  def destroy
    @survey.delete
    redirect_to '/'
  end
  
  def preview
    
  end
  
  def link
  
  end
  
  private
  def find_survey_id
    @survey = Survey.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/multiples_helper.rb
module MultiplesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responsers_helper.rb
module ResponsersHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!--부트스트랩 CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--fontawesome-->
    <script src="https://kit.fontawesome.com/45b9b7b830.js"></script>  
    <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
    <!--<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->
    
    
    <!--modal-->
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    
    
    
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    <!-- -->
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <!-- -->
    <title>한방에 취합하기 MOA</title>
  </head>

  <body>
    <header class="navigation fixed-top">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <%#= link_to "메인으로", "/" %>
        <%= link_to root_path do %>
          <img src="<%= asset_path 'logo.png' %>", height="60">
        <% end %>

        
        
          <div class="collapse navbar-collapse text-center" id="navigation">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to current_user.email, surveys_path, :class => "nav-link" %> <!-- 자신의 계정 클릭 시 자신의 설문 목록-->
                </li>
                <li class="nav-item">
                  <%#= link_to "로그아웃", destroy_user_session_path, method: :delete, :class => "nav-link" %>
                  <%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: {confirm: "로그아웃 하시겠습니까?"},class: 'nav-link' %>
                </li>
              <% else %>
                <li class="nav-item">
                <%= link_to "로그인", user_session_path, :class => "nav-link" %>
                </li>
            </ul>
          </div>
        <% end %>
      </nav>
    </header>
    
    <%= alert %>
    <%= notice %>
    <%= yield %>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>